import esbuild from "esbuild";
import process from "node:process";

const mode = process.argv[2] ?? "production";
const watch = process.argv.includes("--watch");
const isProd = mode === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/WdBlink/agent-notebook
*/`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: {
    main: "src/main.ts",
    styles: "src/plugin.css"
  },
  bundle: true,
  external: ["obsidian", "node:*"],
  format: "cjs",
  target: "es2022",
  platform: "browser",
  sourcemap: !isProd,
  treeShaking: true,
  outdir: ".",
  entryNames: "[name]",
  logLevel: "info",
  define: {
    "process.env.NODE_ENV": JSON.stringify(isProd ? "production" : "development")
  }
});

if (watch) {
  await context.watch();
  console.log("[agent-notebook] watching plugin sources");
} else {
  await context.rebuild();
  await context.dispose();
}
