import esbuild from "esbuild";
import process from "node:process";

const mode = process.argv[2] ?? "production";
const watch = process.argv.includes("--watch");
const isProd = mode === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/WdBlink/daily-cockpit
*/`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian"],
  format: "cjs",
  target: "es2022",
  platform: "browser",
  sourcemap: !isProd,
  treeShaking: true,
  outfile: "main.js",
  logLevel: "info",
  define: {
    "process.env.NODE_ENV": JSON.stringify(isProd ? "production" : "development")
  }
});

if (watch) {
  await context.watch();
  console.log("[daily-cockpit] watching src/main.ts");
} else {
  await context.rebuild();
  await context.dispose();
}
